### ISSUE TITLE
for of文で置き換えるべきfor文がある

### ISSUE THREAD

**Issue by subscline-seiichi-shinomiya** [AjisaiHachimitsu/counter_by_svelte#4]
https://github.com/AjisaiHachimitsu/counter_by_svelte/blob/a4d8cd3b7d6770ff6f0042b790154f6593f5e5b7/src/counter.ts#L29-L32
@AjisaiHachimitsu この場合は単なるfor文より**for of文**を使ったほうがいいですね。
細かいですが修正していただくことは可能でしょうか？

参考：https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...of

**Comment by subscline-seiichi-shinomiya** [comment]
@AjisaiHachimitsu ちなみにreduceというメソッドを使って合計値を計算することもできますね

**Comment by AjisaiHachimitsu** [comment]
個人的に通常のforのほうが好きでしたが、for ofの方が見やすいですね。
今後はfor of が使える場面では使おうと思います。
