### ISSUE TITLE
記号の前後に空白がなくて不自然な箇所がある

### ISSUE THREAD

**Issue by subscline-seiichi-shinomiya** [AjisaiHachimitsu/counter_by_svelte#5]
記号の前後に空白スペースが無くて違和感を感じる箇所が多数ありました。
もちろん動作に悪影響はないですが、世の中のほとんどのソースコードが記号の前後に空白をいれる共通の方針で書かれているので合わせたほうがいいと思います。

例えば次のコードは
https://github.com/AjisaiHachimitsu/counter_by_svelte/blob/a4d8cd3b7d6770ff6f0042b790154f6593f5e5b7/src/counter.ts#L16
↓のように書かれるのが一般的です。
```typescript
if (this.count >= 1)
```

全箇所を手動で修正していくのは大変なのでPrettierという自動整形ツールを使ってみるのがおすすめです。
ぜひチャレンジしてみてください 👍

**Comment by AjisaiHachimitsu** [comment]
コメントありがとうございました。
フォーマットを実行しました。
今まで一人で書いていたのでそんなに気にしていませんでした。
