### ISSUE TITLE
初期のカンマを消去する。

### ISSUE THREAD

**Issue by pon0204** [AjisaiHachimitsu/counter_by_svelte#7]
お疲れ様です!!
inputフォームが空の場合に、末尾のカンマ(初期のカンマ?)が残ってしまっているので消去していただけると!

<img width="1512" alt="Fullscreen_2022_04_21_12_19" src="https://user-images.githubusercontent.com/70616489/164365352-5b1d22f1-cb39-4872-a180-25500b22198f.png">

**Comment by AjisaiHachimitsu** [comment]
コメントありがとうございました。
タイトルが空のカウンターも残したほうがいいかなとも思っていたのですが削除しました。

**Comment by pon0204** [comment]
> タイトルが空のカウンターも残したほうがいいかなとも思っていたのですが削除しました。

あ、ホントですね。。🙇‍♂️
特に直す必要ありませんでした 🙇‍♂️
(修正前のものに戻す必要はないです。)

お手数おかけしました。。 🙏
